name: "TransferAPI"
api: ["4.0.0", "5.0.0"]
version: "1.0.0"
description: "Public TransferAPI for WaterdogPE for PocketMine Server"
main: TransferAPI\Main
author: "BlckqPlugins"

permissions:
  transferapi.sendto:
    description: SendTo Command Permission
    default: op